### PR TITLE
All themes: add selectable metacity theme with borders

### PR DESCRIPTION
**Pull request by raveit65**
This will add a second selectable theme for using without
compositor and invisible borders.

### CODE REVIEW

**Comment by raveit65** [comment]
Please do not merge for the moment. I like to do the same for other themes too.

**Comment by lukefromdc** [comment]
I can confirm that both themes show up and that the buttons move slightly to accomodate the border. Window resizing seems similar though on both: touchy but not 1px touchly like BlackMATE from master

**Comment by raveit65** [comment]
@lukefromdc @sc0w 
Feel free to do the same for your themes and add it to PR.

**Comment by lukefromdc** [comment]
Had to rebase against master and then apply a commit restoring the original 1px borders for BlackMATE, reverting b9cfbf2c22d32a44283b168d27cb428ca15ffba6 for BlackMATE since the same change is applied for BlackMATE-border

When all of this this gets into a release (should NOT be prior to the Marco work being included in a release, presumably meaning marco 1.24), it should be documented both in the release notes and somewhere in marco's manpage

**Comment by raveit65** [comment]
Very nice.
I just added BlackMATE-border to po/POTFILES.in to fix distcheck.

**Comment by raveit65** [comment]
@lukefromdc 
There is a plan adding invisible-borders to 1.22 branch, to get it into ubuntu-19.10.
Personal i see that as a long outstanding bugfix and i will add it to fedora when it is ready.

**Comment by lukefromdc** [comment]
Good to know, then this does not have to wait for 1.24

**Comment by vkareh** [comment]
@raveit65, can you please bring back the rounded bottom corner for GreenLaguna theme? It's available in metacity-theme-2, but it went away in metacity-theme-3

**Comment by raveit65** [comment]
@vkareh 
I just update metacity-theme-3 for  GreenLaguna and round bottom corners are back.
Not sure what i should do with frame_geometries `small`, `small_unfocused` and `border`, `borderless` and `modal`, because i don't know where are those frame_geometries are used?

**Pull request merged**
