### PR TITLE
Menta themes: Use high resolution window control assets

### PR DESCRIPTION
**Pull request by vkareh**
This adds higher resolution window controls and explicitly sets the
lower resolution size in the image <draw_ops>. This allows marco to
determine the intended size to be used for either LoDPI or HiDPI
rendering.

Needs https://github.com/mate-desktop/marco/pull/561

### CODE REVIEW

**Comment by raveit65** [comment]
The control buttons (min/max/close are looking really sharp now with HIDIPI, good job.
Only the window-menu button looks blurred here for some reasons.

Btw. i am still wondering that the control buttons are sharp with metacity WM?
Here the menu button isn't visible. But maybe this is related to a setting by metacity WM.
And the min/max/close buttons for CSD windows are blurred. Menta themes are shipping own images for buttons in csd windows. https://github.com/mate-desktop/mate-themes/tree/master/desktop-themes/BlueMenta/gtk-3.0/window-controls
But i guess this scaling job is (not) done by GTK itself?
Or do we need SVGs here?

**Comment by flexiondotorg** [comment]
Windows controls in CSD applications do not appear blurred on my HiDPI or regular DPI displays. I have also recently disabled the menu button in Ubuntu MATE 19.10.

**Comment by raveit65** [comment]
@flexiondotorg 

> Windows controls in CSD applications do not appear blurred on my HiDPI or regular DPI displays

With Menta themes?

**Comment by vkareh** [comment]
Thanks for testing this. We should also make sure that this doesn't regress on either Metacity, Compiz, or Compiz Reloaded.

I've already tested on metacity and marco, and since both compiz (compizes?) are based on these, I suspect they should be fine.

**Comment by raveit65** [comment]
@vkareh 
I don't think that windows-menu button is scaled.
menta-buttons
Is that because of using PNGs ?
But you changed something with that images.
```
 desktop-themes/BlueMenta/metacity-1/menu.png  | Bin 314 -> 562 bytes
 .../BlueMenta/metacity-1/menu_prelight.png    | Bin 272 -> 565 bytes
```

@flexiondotorg 
Are you really sure that buttons from dconf-editor CSD window are scaled in ubuntu?
Here in fedora they aren't scaled.
Menta-CSD-Buttons

@vkareh 
Again my question. This should be done by GTK ?

**Comment by vkareh** [comment]
@raveit65 - I'll improve the menu button, I might have not scaled it enough (it was a different file than the rest, so the process for scaling it was different).

Regarding CSD headers, it's odd that Menta doesn't scale them. Seems to scale correctly with the Ambiant-MATE themes, even before my changes in marco... :confused:

**Comment by raveit65** [comment]
@vkareh 
I think Ambiant/Radiant-MATE themes are using standard buttons from GTK itself.
Menta use own buttons, see https://github.com/mate-desktop/mate-themes/tree/master/desktop-themes/BlueMenta/gtk-3.0/window-controls

**Comment by raveit65** [comment]
Yes, Ambiant-Mate doesn't use own buttons for CSD-controls.
Menta themes use a own `window-controls.css` to add own images.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/window-controls.css
But it uses PNGs.
Maybe this can be improved when using the SVGs from metacity theme folder.

**Comment by vkareh** [comment]
I'm creating new PNGs for the CSD themes on my local branch and it seems to work. I'll push new changes in a bit.

**Comment by raveit65** [comment]
CSD buttons and window-menu buttons are fine with latest changes. :)

**Pull request merged**
