### PR TITLE
TOK/Green Remove gradient from notebook header

### PR DESCRIPTION
**Pull request by mrnhmath**
This should make notebook more clean visually and more in line with Clearlooks.
captura de tela de 2017-05-28 19-25-33

### CODE REVIEW

**Comment by raveit65** [comment]
This removes cleanly the gradient background from notebook headers.
But i don't want to decide this change, as i don't use  and i don't like trad themes.
So up to maintainer or @monsta to approve this change :-)

PS: personal i would simply delete it to avoid work ;-)

**Comment by monsta** [comment]
Well, I already commented at https://github.com/mate-desktop/mate-themes/pull/162 on this subject: I would prefer solid color like in GTK+2.

**Comment by sc0w** [comment]
rebased, renamed, and merged in https://github.com/mate-desktop/mate-themes/commit/1d148f45b89ed63961af8c006b80c982e8bffda8

@mrnhmath thanks

**Comment by sc0w** [comment]
Note to avoid possible confusions, the change with this PR is here: (gray gradient)

image4493

**Comment by monsta** [comment]
Ah... I didn't realize that. Well, I never noticed a gradient there :slightly_smiling_face:

**Pull request closed without merging**
