### PR TITLE
all themes: Mate Panel: Fix align with CheckBoxes in applet popup menu

### PR DESCRIPTION
**Pull request by sc0w**
This PR needs to test in combination with https://github.com/mate-desktop/mate-panel/pull/789

### CODE REVIEW

**Comment by raveit65** [comment]
Can we use this for Menta and Submarine themes
```
/* checkboxes in applet popup menu */
.mate-panel-menu-bar menu > menuitem > box > menuitem {
    padding: 0px 3px 0px 4px;
}
```
This moves the text of the entry to the right position.
GreenLaguna and BlackMate have already a padding setting the menuitem which conflicts with the new one.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlackMATE/gtk-3.0/mate-applications.css#L260
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/GreenLaguna/gtk-3.0/mate-applications.css#L287

**Comment by sc0w** [comment]
@raveit65 

I think `" .mate-panel-menu-bar menu > menuitem > box > menuitem "` doesn 't affect other items, I can handle it with `margin` instead `padding`, what do you think?

**Comment by raveit65** [comment]
What i meant is that BlackMate and Greenlaguna have already a setting which moves the checkbox without the PR.
See how it looks with those themes without the PR.
For this reason your settings doesn't have any effect.
You need to adjust old settings or remove old settings and add your new setting.

**Comment by sc0w** [comment]
> For this reason your settings doesn't have any effect.

It works fine here, this PR fixes the alignment:

blackmate

green

and it works with menta and submarine themes too

do you have tested with the latest changes of mate-panel PR?

**Comment by raveit65** [comment]
Ok , all is different now after rebuilding mate-panel with right patch version.
Menta themes --> good.
Submarine themes --> good
Traditional themes --> good
GreenLaguna --> good, only.....
Can you move the setting for GreenLaguna under
```
/* set normal menu menuitem */
.mate-panel-menu-bar menu menuitem {
    padding: 3px 6px;
}
/* checkboxes in applet popup menu */
.mate-panel-menu-bar menu > menuitem > box > menuitem {
    padding: 0px 0px 0px 3px;
}
```
please?

And for BlackMate i would use 
```
/* checkboxes in applet popup menu */
.mate-panel-menu-bar menu > menuitem > box > menuitem {
    padding: 0px 0px 0px 1px;
}
```
But should be decided by @lukefromdc

**Comment by raveit65** [comment]
> I don't agree, the alignment is wrong with padding: 0px 0px 0px 1px;

I do not really care ;)

**Comment by raveit65** [comment]
Not sure when we should push that to gtk3.22 branch from where i create releases.
Maybe we push it only to master and wait until related commit is in stable panel release?
Or we leave this PR open as reminder to avoid we forget about?

**Comment by sc0w** [comment]
the mate-panel PR is merged, so, this PR needs to be merged too

I think it can be pushed to gtk3.22 too if you like, because this PR doesn't affect the behavior of older mate-panel versions

**Pull request merged**
