### PR TITLE
Added a new dark desktop theme

### PR DESCRIPTION
**Pull request by nokangaroo**
A new dark desktop theme

The theme is based on BlackMATE (at least that was my starting point). There should
be more dark themes - the ubiquitous contrast-poor whiteout hurts my eyes.

I'll be grateful for constructive criticism - I'm sure I have overlooked some
things that I don't use on my desktop, and no doubt some things could be done
differently. I used gtk3-widget-factory and gtk3-demo (and of course MATE) for
reference, and things seem to work.

The gtk3 version comes in 2 flavors of darkness. The gtk2 theme follows the
lighter version.

The openbox theme is my own (mostly). The metacity theme is copied from BlackMATE,
with minimal adaptations. I haven't figured out yet how to lose the compositing
shadows; probably a bug in Marco. I would be comfortable with
```
.background.csd decoration {
	border-radius: 0px 0px 0px 0px;
	border-width: 0px;
	box-shadow: 0 0 0 2px @base_color;
	/* this is used for the resize cursor area */
	margin: 10px;
}
```
which means no compositing shadow for undecorated windows (gtk3-widget-factory),
but all other windows will still have shadows (which looks horrible and unrealistic -
the light should come from one direction only).

The "apps", "unity" and "cinnamon" folders and the corresponding css files were
deleted (I don't use those programs, so I can't modify theme settings for them.
I'm simply assuming that gtk3-widget-factory and gtk3-demo are the canonical
references).

### CODE REVIEW

**Comment by lukefromdc** [comment]
I just tested your theme (with GTK 3.22.15), it works though I'd advise you to apply these two commits to fix CSD issues:
https://github.com/nokangaroo/mate-themes/commit/49ba969813649c19f767ad6d22f350a173ddb9df
https://github.com/nokangaroo/mate-themes/commit/1ba65d1a7bb83ed374e817b386cc49aa61379c85


I also have a mixed light and dark theme based on the circa 2008 UbuntuStudio theme and closely maintained at:
https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy

**Comment by nokangaroo** [comment]
Thanks! Should I withdraw this pull request and create a separate repo just for
this theme (since I'll keep working on it) or can I have both?

**Comment by lukefromdc** [comment]
If you apply the commits to the branch the PR would merge, they will be automatically included.

**Comment by raveit65** [comment]
Who will maintain another theme?
I have a work overload, so i can't....

**Comment by nokangaroo** [comment]
I would maintain the theme myself in any case.

I'm not sure those commits will help. With openbox I have csd problems even with
BlackMATE. I can't make the black corners of the "it is now safe" notification
go away (that's why I use the "standard" notification theme - the only one that
works). It seems that gtk3 simply does not work properly without compositing. Or
it might be a bug with the notification theme - I am really tired of repeatedly
plugging and unplugging a usb stick to see the notification because the preview
in mate-control-center is unreliable. Everything else seems to work though. Can
you give me a specific example of an application that shows up csd problems so I
can install it and see for myself?

**Comment by lukefromdc** [comment]
I don't have time to maintain a 3ed theme myself. If we want to add another theme, could use mine with a rename (due to the UbuntuStudio trademark) to something more generic (maybe mate-mulitmedia-dark?) as it gets intensive maintainance. Don't know how much demand there is for it, but the Archive page has accumulated around 2,000 downloads with all the theme and mate package updates to it.

**Comment by lukefromdc** [comment]
BTW, round corners are not possible with a noncompositing WM (certainly not supported by GTK3) without some special hacks due to the fact that X can only draw rectangular windows and uses 3 channel RGB video. Any noncompositing WM that draws rounded corners had to do so by copying the background into that part of the window and then drawing over it. That's how mate-panel draws a transparent panel on a noncompositing window manager, and that works with any GTK version.

GTK themes intended for use with noncompositing window managers  use the .solid-csd style class to force square corners and no black rectangle around the window. I just realized BlackMATE does not have this and thus did not before I ported it to GTK 3.20 last year. I normally use compiz, don't have openbox installed but do have marco and metacity, which can be tested with or without compositing

BlackMATE is not my day to day theme so it does not get the level of attention that ubuntustudio-legacy does but I try to keep up with the bugs. I'll have a look at this tomorrow. Difference will be subtle though, as the only visible difference will be squaring off a subtle rounded border appearing within a slightly larger gray square, and by removing box shadow shrinking that square back down to the actual window size.

**Comment by lukefromdc** [comment]
Fix for noncomposited headerbar showing rounded corners within square noncomposited decorations in BlackMATE now pushed to master, GTK 3.22, GTK 3.20 and fix-chrome

**Comment by raveit65** [comment]
> I don't have time to maintain a 3ed theme myself. If we want to add another theme, could use mine with a rename (due to the UbuntuStudio trademark) to something more generic (maybe mate-mulitmedia-dark?) as it gets intensive maintainance. Don't know how much demand there is for it, but the Archive page has accumulated around 2,000 downloads with all the theme and mate package updates to it.

I am fine with it.

@nokangaroo 
If i am understanding you correctly, you need this theme only for openbox?
Why not adding a openbox folder to BlackMate like in other themes?
Or does your changes affect also gtk+3 with other WMs like marco or metacity.
Don't understand me wrong but maintaining a theme needs a bit of constant work.
Currently it's easy because most distros use 3.22 as gtk+3 version.
But i am sure with gtk+-4 we need to make extra adjustments again.
That all means you need to test a theme for different gtk+ versions.
And you need to support applications which you don't use for ourself.

@flexiondotorg @monsta 
What do you think about?
a) adding @lukefromdc  theme
b) adding @nokangaroo theme + adding him to mate-themes maintainers?

**Comment by raveit65** [comment]
Opps, i forgot to call @sc0w  for asking about

**Comment by nokangaroo** [comment]
I just installed xcompmgr, which works fine with openbox and solves the CSD issue. And it has NO shadows, hurrah!

**Comment by flexiondotorg** [comment]
It's great to see another theme being created for MATE ☺️

However this seems like it's for a niche audience. Is it really suitable to inclusion here or should this be maintained in its own repo?

**Comment by nokangaroo** [comment]
I propose creating my own repo for this theme (I hadn't really thought this through; I know from experience how much work it is to maintain the theme). So I would push to my own repo from now on if you decide against adding my theme. As for lukefromdc's theme, if he is willing to maintain it, go for it! I looked at it, and I like it. I am adding another commit to my fork, but it will be the last for now. I will close this as soon as you make a decision.

**Comment by sc0w** [comment]
@raveit65 

> Opps, i forgot to call @sc0w for asking about

@lukefromdc is the black mate maintainer, and this is a fork, so, I agree with his thoughs

**Comment by nokangaroo** [comment]
Okay, let's end the suspense. I'll create my own repo. I think people who use LXDE
might be interested; they didn't have any dark themes last time I looked. I already
briefly tried this theme with lxde-gtk3; it needs a few tweaks but it should work.
Thanks for your time.

**Pull request closed without merging**
