### PR TITLE
Traditional*: Fix selectors for toolbar buttons

### PR DESCRIPTION
**Pull request by jsane-h8ms**
I can only assume this was a mistake.

It caused artifacts visible in gtk3-widget-factory for instance, in the expander toolbar buttons. The images are not supposed to have extra borders. See attached screenshot
traditionalok
.

### CODE REVIEW

**Review by raveit65 — APPROVED** [review]
That's simply a mistake in syntax, ready to go.
Edit: see Menta themes which is our references.

**Review by zhuyaliang — APPROVED** [review]

**Comment by lukefromdc** [comment]
Just tested myself and can confirm this works

**Comment by opk12** [comment]
Sorry for the OT. @jsane-h8ms Could you please tag a release for [clearlooks-phenix](https://github.com/jsane-h8ms/clearlooks-phenix), so that jpfleury's version can be replaced with your fork at Debian ([details](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961834#21)) and Arch ([details](https://aur.archlinux.org/packages/clearlooks-phenix-gtk-theme#comment-867542))? This would also fix most of Debian's bugs ([list](http://bugs.debian.org/clearlooks-phenix-theme)). You may want to merge the patches from Arch ([list](https://aur.archlinux.org/packages/clearlooks-phenix-gtk-theme#pkgsrcslist)). Could you also enable issues on the repo, as a communication channel? Thank you very much.

**Comment by raveit65** [comment]
Wrong repo? Please use https://github.com/jsane-h8ms/clearlooks-phenix for discussions.
...to avoid email notifications in MATE.

**Pull request merged**
