### PR TITLE
Write theme names in title case

### PR DESCRIPTION
**Pull request by rbuj**
Screenshot at 2021-02-09 17-04-26

### CODE REVIEW

**Comment by lukefromdc** [comment]
This actually renames all themes, I can see many potential issues affecting users with customized themes from this

**Comment by rbuj** [comment]
It should only affect the display name, as the theme name is in the path to the index.theme file.

**Comment by raveit65** [comment]
I do not see any reason why we should rename the displayed name of a theme.
When eg. `BlueMenta` is  the name of a theme than `BlueMenta` is the name.
I mean, what do think when some one wants rename `Robert` in `Ro` and ` Bert` :)
I gave my baby the name (Blue)Menta, why should it get a new name with 6 years ?

:-) :-) :-) :-) :-) :-) :-) :-)

**Comment by rbuj** [comment]
It's a localized string and it only affects to English text.

There are two themes which don't use the camel case, High Contrast and High Contrast Inverse. They use title case.

**Comment by rbuj** [comment]
Ro Bert makes more sense if you speak German. ;-D

> The name Robert is an ancient Germanic given name, from Proto-Germanic *Hrōþi- "fame" and *berhta- "bright" (Hrōþiberhtaz).

https://en.wikipedia.org/wiki/Robert

**Comment by raveit65** [comment]
Ok, that works and it is fine for the GUI, but i see a naming mismatch with gsettings keys which we use. Eg.
```
[rave@mother ~]$ gsettings get org.mate.interface gtk-theme
'BlueMenta'
[rave@mother ~]$ gsettings get org.mate.Marco.general theme
'BlueMenta'
```
So a different naming can be confusing for users.

**Comment by rbuj** [comment]
This key refers to the name shown in the dialogs, which is [localized](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html):
```
$ grep Name /usr/share/themes/BlueMenta/index.theme 
Name[ca]=Menta blau
Name[cs]=Modrá Menta
Name[da]=BlueMenta
Name[es]=Menta azul
Name[fr]=BlueMenta
Name[gl]=AzulMenta
Name[hu]=Kék menta
Name[hy]=Կապույտ-Menta
Name[id]=BlueMenta
Name[it]=BlueMenta
Name[kab]=MentaAnili
Name[lt]=Mėlyna Menta
Name[ms]=BlueMenta
Name[nb]=BlueMenta
Name[nl]=BlauwMint
Name[oc]=BlueMenta
Name[pl]=BlueMenta
Name[ru]=Menta (Синяя)
Name[sr]=Плава мента
Name[sv]=BlueMenta
Name[tr]=MaviMenta
Name[uk]=Блакитна М'ята
Name[zh_CN]=薄荷蓝
Name[zh_TW]=BlueMenta
Name=BlueMenta
```

**Comment by rbuj** [comment]
Catalan screenshot: `LANG=ca_ES.UTF-8 mate-appearance-properties`

Screenshot at 2021-04-25 20-24-15

Note Catalan language doesn't use camel case such as English language.

**Comment by raveit65** [comment]
What dos this have to do with my concern?
We have different naming in GUI and gsettings key which can confuse users.

**Comment by raveit65** [comment]
I don't see any reason to rename themes in GUI.
It makes only a problem.
I disagree with PR.

**Review by raveit65 — CHANGES_REQUESTED** [review]
This makes a mismatch between theme name in GUI and gsettings theme name.
This is not a good idea.

**Comment by rbuj** [comment]
I think you are confused with the Name, GtkTheme and MetacityTheme keys, since Name has a localitzed value unlike the other two keys.

**Comment by raveit65** [comment]
....don't tell other people that they are confused.
You are the one who don't want to understand.

**Comment by rbuj** [comment]
I think you are the one who don't want to listen... and please check the actual purpose of this key.

The Name key refers to the descriptive name displayed to the user [1], for this reason it has a [localized value](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html), that is to say it can be translated, and the translators translate it into their languages bearing in mind that it's a [common noun](https://en.wikipedia.org/wiki/Proper_and_common_nouns) and not a proper noun.

[1] https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
> short name of the icon theme, used in e.g. lists when selecting themes.

**Comment by rbuj** [comment]
Captura de Pantalla 2021-04-26 a les 14 50 48
https://docs.oracle.com/cd/E19957-01/817-5310/6mkpbn3tl/index.html

**Comment by raveit65** [comment]
As author of most themes i do not agree!
I will revert it when you merge it.

**Comment by rbuj** [comment]
ok, don't worry

**Comment by raveit65** [comment]
Honestly, i do not really understand why you ignore the opinion of 2 other team members.
But i will try to explain it with a picture again.
Bildschirmfoto zu 2021-04-26 17-54-19
As you can see  m-a-p use you PR with new names, but the gsettings key use directory name from `/usr/share/themes/BlueMenta`.
For me this is a naming mismatch which can confuse users.
Keep in minds that distro maintainers use the gsettings key for gsettings overrides.
For this reason i am against a renaming.
It is normal in a team that not all people do agree with every idea.
Not a reason to close all other PRs....

**Comment by rbuj** [comment]
ok, don't worry

**Comment by rbuj** [comment]
> It is normal in a team that not all people do agree with every idea.
> Not a reason to close all other PRs....

I've gotten too involved in this project and maybe it’s better to take a break. I don't want my break could affect other developers. For this reason, I closed my pending contributions, because I'll probably take a long time to give feedback or apply the suggested changes. I hope you understand it. I ❤️ MATE. Yours truly, Robert.

**Comment by raveit65** [comment]
You're welcome.

**Pull request closed without merging**
