### PR TITLE
Make Notebook more traditional

### PR DESCRIPTION
**Pull request by mrnhmath**
I also removed the dashed outline. I will investigate a better solution that matches the original theme more.

captura de tela em 2017-05-09 15-03-38

### CODE REVIEW

**Comment by lukefromdc** [comment]
Will removing outlines disable keyboard navigation, or is that not an issue with the traditional themes? Ideally this would be done the way it was done in GTK2 if that is even possible. Overall preserving keyboard navigation capability without making a theme ugly has always been difficult, it seems like GTK3 offers lots of easy ways to make something ugly and harder ways to make the same thing pretty.

**Comment by mrnhmath** [comment]
Ambiance have a pretty outline that resembles the original Clearlooks, but orange. I can reuse it.

**Comment by raveit65** [comment]
Notebook  section is a very complicate section with gtk+-3.20. Simply override all without real knowing what you, do will cause a lot of problems.
You only need to edit 'tabs' stuff.

**Comment by mrnhmath** [comment]
I'm learning :-) I checked all areas that tabs are applied before making the request, there's still some things to do.

**Comment by sc0w** [comment]
a lot of changes in one unique commit, I prefer a lot of commits for better analysis, or various PRs, step by step, here are mixed outlines, notebooks, borders, padding...

I don't agree with remove outlines, we need to fix that, but the remove is not the solution

**Pull request closed without merging**
