### PR TITLE
Traditional themes: use gradient color on active tabs

### PR DESCRIPTION
**Pull request by sc0w**
I like to respect the gtk2 aspect on gtk3

I think the tabs looks better

### CODE REVIEW

**Comment by raveit65** [comment]
We have 4 different notebooks, see gtk3-widget-factory first page.
notebook header.{top/bottom/left/right} tab:checked
See the commit where the color was removed as reference
https://github.com/mate-desktop/mate-themes/commit/cffe88c88e748058de7917b260cf3181a5922329

**Comment by sc0w** [comment]
@raveit65 understood, thanks for the info

commit rebased

**Comment by raveit65** [comment]
This is notebook_active_tab_border ?
or menubar_menuitem_hover_border_color = shade(@core_color_a, 0.58) ?
Sadly, using gtk3-inspector is a bit limited with tabs in GtkNotebook.
The selector notebook header.top tab {} isn't shown,
only notebook {}.
But a while ago i needed to fix pavucontrol which does not use a own selector at top hierarchy.
In result i was forced to add a override for mate-terminal.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/TraditionalOk/gtk-3.0/mate-applications.css#L522
You need to edit the code block like this in mate-application.css
```
/* override settings for pavu-control */
window.background.mate-terminal > box.vertical > notebook > header.top tab,
window.background.mate-terminal > box.vertical > notebook > header.top tab:checked,
window.background.mate-terminal > box.vertical > notebook > header.top tab:checked:hover {
    border-radius: 3px 3px 0px 0px;
    padding: 4px 2px 4px 6px;
    margin: 0px 0px 0px -1px;
    border-style: solid;
    border-color: @border_color;
    border-width: 1px;
}

/* override settings for pavu-control */
window.background.mate-terminal > box.vertical > notebook > header.top tab:checked,
window.background.mate-terminal > box.vertical > notebook > header.top tab:checked:hover {
    border-bottom-color: @notebook_active_tab_border;
    border-top-color: @notebook_active_tab_border;
}
```
This is a very good example why it is good to have a own specific selector for every application, like
window.background.mate-terminal
Only for pavucontrol we need to edit other applications.

**Comment by sc0w** [comment]
this is notebook_active_tab_border

with gtk3-inspector it works fine with same code, but with mate-themes installed on the system it doesn't work

I will investigate mate-application.css

**Comment by raveit65** [comment]
> with gtk3-inspector it works fine with same code, but with mate-themes installed on the system it doesn't work

Of course, gtk3-inspector override every theme.css.
I such a case you have to look what is after the mentioned code in gtk3-widgets.css
And mate-application.css is the last file which is used, see
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/TraditionalOk/gtk-3.0/gtk.css#L509

**Comment by monsta** [comment]
Hmm, I don't remember how it looked in GTK+2. Was there a gradient?

As for GTK+3, I see just a colored line on the top of tab with 3.18 (solid color, no gradient), and no colored line at all with 3.22. That's w/o this PR, I didn't try it yet.

**Comment by sc0w** [comment]
@raveit65 

thanks for the additional information

commit rebased

@monsta 

yes, gtk2 had a color gradient, you can see https://github.com/mate-desktop/mate-themes/issues/159#issuecomment-272999256 with screen captures

the gtk3 solid line was removed in https://github.com/mate-desktop/mate-themes/commit/cffe88c88e748058de7917b260cf3181a5922329

**Comment by monsta** [comment]
Weird... I ran GTK+2 build of Pluma and didn't see a gradient with TraditionalGreen:

pluma-tabs

**Comment by raveit65** [comment]
i see an green gradiant on active tab in your screenshot :-)

**Comment by sc0w** [comment]
@monsta 

ups, sorry, I was wrong, the theme is "shiny" on debian jessie (gtk2) with this color gradient

**Comment by monsta** [comment]
Ok, that clears the confusion :slightly_smiling_face: 

Personally, I'd re-introduce just a colored line, like on my screenshot above, into GTK+ 3.22 theme... it matches other aspects of Traditional themes (or Clearlooks-Phenix if you wish).

**Comment by sc0w** [comment]
but, the gtk3 appareance with that solid line, is erroneus

see the differences, your capture with gtk2

pluma-tabs

and gtk3

greentg

and this gtk3 capture

gtk3pluma

the solid color line on gtk3 is erroneus

more captures

mate-terminal

gtk2

tokmtgtk2

and gtk3

tokmtgtk3

so, with gtk2, I agree, the appearance is fine

but, with gtk3, the tabs seem to be wrong

**Comment by sc0w** [comment]
merged in https://github.com/mate-desktop/mate-themes/commit/df8dcca39b9b4149f8c2cc5f6fbffb9cbf22c555

**Pull request closed without merging**
