### PR TITLE
gtk-widgets.css: Add the missing .context-menu class

### PR DESCRIPTION
**Pull request by rbuj**
See https://github.com/mate-desktop/pluma/pull/582#issuecomment-710752054

### CODE REVIEW

**Comment by raveit65** [comment]
Can you please add a description to css code?
So that we know for what it is good for.
```
/* Decouple the font of context menus from their entry/textview */
.context-menu {
        font: initial;
        text-shadow: none;
}
```

**Comment by rbuj** [comment]
@raveit65 done

**Review by raveit65 — APPROVED** [review]
LGTM.
Thanks.

**Comment by lukefromdc** [comment]
While late to test this with all else going on in my life, I can confirm that the relevent changes to Pluma 
https://github.com/mate-desktop/pluma/pull/582
first brought back monospace fonts in the contest menu, and that this in turn restores the correct behavior. Added this exact same code to
https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy
with
https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy/commit/c50892f55bf240fa86ae9689337cd115f0547e2d

Anyway, one more tester prior to this going to a release

**Pull request merged**
