### PR TITLE
all themes: xrandr-applet menu styling

### PR DESCRIPTION
**Pull request by lukefromdc**
Support new xrandr applet popup theming. In most themes remove the monitor label background

### CODE REVIEW

**Comment by raveit65** [comment]
@lukefromdc @sc0w @monsta 
Dear theme maintainers if you like to change something in your themes......go ahead.

**Comment by monsta** [comment]
Hmm... the commented parts look like they would affect other disabled labels and possibly other widgets too?

**Comment by lukefromdc** [comment]
Normally things like 
```

 label,
 label:disabled {
     background-color: transparent;
 }
```
don't seem to be needed anymore, with at least GTK 3.22 apparently defaulting to this. I removed it last week from my UbuntuStudio_Legacy theme and have yet to notice any side effects from it in daily use.

**Comment by raveit65** [comment]
I just updated Menta themes and did a forced-push, now they looks really bad.....

@monsta 
> Hmm... the commented parts look like they would affect other disabled labels and possibly other widgets too?

No, i posted it already in another post related to this changes
Eg.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/gtk-widgets.css#L95
```
image,
image:disabled,
label,
label:disabled,
box,
box:disabled,
grid,
grid:disabled {
	background-color: transparent;
}
```
Code blocks like this are remnants from < gtk+-3.20 css syntax.
There is no reason to set a transparent color for a widget if nothing else before in css set up a color here.
Also, using wildcards like this is a bad behaviour, because you never know which widgets do you match.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/gtk-widgets.css#L50
In Submarine theme i have removed such wildcards a while ago. This is a TODO for other themes.

**Comment by monsta** [comment]
Ok, so I get different results with various themes (and m-s-d built from git master).

Adwaita (which surely doesn't override anything):
virtualbox_debian testing_23_05_2018_13_30_26

BlackMATE:
virtualbox_debian testing_23_05_2018_13_30_41

Menta:
virtualbox_debian testing_23_05_2018_13_31_00

**Comment by monsta** [comment]
I guess this needs some corrections either here or in m-s-d.

**Comment by raveit65** [comment]
You did not applied https://github.com/mate-desktop/mate-settings-daemon/pull/224
Than adwaita use black font-color.
BlackMate and Menta in your screenshots reflects theme settings from this PR.

**Comment by monsta** [comment]
Yes, I tested git master so far, will try https://github.com/mate-desktop/mate-settings-daemon/pull/224 too.

**Comment by monsta** [comment]
Ok, Adwaita has black text color now.

**Comment by raveit65** [comment]
Menta themes are updated for https://github.com/mate-desktop/mate-settings-daemon/pull/226

**Pull request merged**
