### PR TITLE
BlackMATE:fix Chrome URL bar so it matches rest of theme

### PR DESCRIPTION
**Pull request by lukefromdc**
Revert previous fix, use the .chromium style class

### CODE REVIEW

**Comment by lukefromdc** [comment]
Awaiting testing by folks with Google Chrome or chromium installed. No obvious negatives in gtk3-widget-factory but needs testing in chrome, this the branch and PR

**Comment by aykevl** [comment]
On Debian stretch, with the BlackMATE theme from desktop-themes/BlackMATE put into /usr/share/themes, I get this result:
screenshot at 2017-06-13 23-49-06
Looks a whole lot better, but still doesn't entirely match the GTK2 appearance: the background and border of the URL bar has gotten a bit lighter.

**Comment by aykevl** [comment]
This looks a bit better to me:

```css
diff --git a/desktop-themes/BlackMATE/gtk-3.0/other-applications.css b/desktop-themes/BlackMATE/gtk-3.0/other-applications.css
index 30d6e94a..f57e1b43 100644
--- a/desktop-themes/BlackMATE/gtk-3.0/other-applications.css
+++ b/desktop-themes/BlackMATE/gtk-3.0/other-applications.css
@@ -311,7 +311,7 @@ window.background.yumex-dnf-window > box.vertical > box.vertical > box.horizonta
 
 .chromium textview.view,
 .chromium textview.view text {
-    background-color: @less_dark_color;
+    background-color: shade(@theme_bg_color, 1.15);
     color: @theme_selected_fg_color;
 }

```
screenshot at 2017-06-14 00-26-41

Note that I have no experience with GTK3 styling, I'm just trying things out.

The white border in the first screenshot appears to be an artifact: the border doesn't always update when switching between styles (even when switching between GTK/classic themes from within Chrome). But when I restart Google Chrome the correct (dark) border color is applied.

There are a few more differences with GTK2 Chromium. For example, there are no light-colored lines in the browser chrome and none of the tested styles have a different window background (behind the tabs) when the window is focused/unfocused (which is the case with GTK2). This may or may not be a problem. See https://github.com/mate-desktop/mate-themes/issues/182#issuecomment-307402390 for older screenshots.

For reference, here is where Chromium defines it's colors:
https://cs.chromium.org/chromium/src/ui/native_theme/native_theme.h

**Comment by lukefromdc** [comment]
I'll leave the detail work on this to those with Chrome installed, a branch and PR are present.

**Comment by aykevl** [comment]
@lukefromdc was the last commit intended to go to this branch?

**Comment by raveit65** [comment]
Interessting that **.chromium** is the general selector for google chrome.
Funny that chromium browser don't need that and displays a dark url bar out of box.
But it looks like that the browser use gtk2 in fedora because of wayland.
http://pkgs.fedoraproject.org/cgit/rpms/chromium.git/tree/chromium.spec#n79

@aykevl 
I agree with background-color adjustment.
Don't worry about last commit as it is a different commit after merge.

**Comment by lukefromdc** [comment]
I should probably strip it from this branch and then rebase the branch on master to avoid getting a merge issue. It was intended to go here but this probably puts it out of order.

**Comment by raveit65** [comment]
@lukefromdc 
I do not really see a different for the csd headerbars in non-compositor case.
Dconf-editor doesn't have round corners. What is the intention of the commit?

**Comment by lukefromdc** [comment]
It is very subtle , but if you look closely a faint rounded headerbar border was visible within the square decoration when compositing was not used. Got a complaint about it in Openbox so fixed it.

Reverted it in this branch, then rebased on master (which has it) for consistancy followed by  a forced update. I had been asked to cherrypick the simple fixes but forgot that on a PR branch it would put commits out of order.

**Comment by raveit65** [comment]
> It is very subtle , but if you look closely a faint rounded headerbar border was visible within the square decoration when compositing was not used. Got a complaint about it in Openbox so fixed it.

Ok.

I would use 
background-color: shade(@theme_bg_color, 1.15);
than it's ready to go.

**Comment by aykevl** [comment]
@raveit65 I'm here comparing "Chromium" as built and shipped by Debian which is built using GTK2, and "Google Chrome" as built and shipped by Google (based on almost the same source code - thus the same identifiers). The difference is which version of GTK they're built with, not the name. Basically, Chromium is the upstream project, and Google Chrome is built using it - similar (but different) to Firefox vs Iceweasel.

**Comment by lukefromdc** [comment]
https://github.com/raveit65 , where are you suggesting
background-color: shade(@theme_bg_color, 1.15)? In the headerbar or for Chrome?

**Comment by raveit65** [comment]
I suggest what @aykevl  already posted :-)
https://github.com/mate-desktop/mate-themes/pull/185#issuecomment-308270679
It's for google chrome

**Comment by lukefromdc** [comment]
OK, it's done by amending the last commit and another forced update so changelogs only show the revert of the previous fix and one commit for this one.

**Comment by aykevl** [comment]
This style restores the background color behind the tabs when the window is selected (like with GTK2):

```css
.chromium menubar:not(:backdrop) {
    background-color: #000000;
}
```

I *think* this color is retrieved at this location: https://cs.chromium.org/chromium/src/chrome/browser/ui/libgtkui/gtk_ui.cc?type=cs&l=897

Still looking for a way to restore the light border on tabs.

**Comment by lukefromdc** [comment]
I've added that latest change to the PR

**Comment by raveit65** [comment]
Hmm, using another backgroung color for the menubar is a good idea for having a better contrast for the tabs, but using black looks not nice for me.
And that we used that color with gtk2 isn't an argument for me.
Gtk2 styling is very limited and switching to gtk3 is a big chance to make it nicer ;-)
My suggestion:
```
.chromium menubar:not(:backdrop) {
    background-color: shade(@theme_bg_color, 0.65);
}
```
This makes a good contrast between menubar and the tabs for me.

**Comment by aykevl** [comment]
Of course :) Looks good to me.
screenshot at 2017-06-15 12-04-56

**Comment by lukefromdc** [comment]
OK, just added 
```
.chromium menubar:not(:backdrop) {
    background-color: shade(@theme_bg_color, 0.65);
}
```
 to the PR

**Pull request merged**
