### PR TITLE
TraditionalOk/Green: Fix title_border bottom attribute

### PR DESCRIPTION
**Pull request by rbuj**
Before

Screenshot at 2020-06-17 12-25-49

After

Screenshot at 2020-06-17 12-24-06

### CODE REVIEW

**Comment by raveit65** [comment]
Weird, i don't see that, with HIDPI.
Bildschirmfoto zu 2020-06-19 12-20-14
But i am fine with it :)
@sc0w 
Does this work for you?

**Comment by raveit65** [comment]
@sc0w 
As maintainer of TOK themes , do you like to fix the issue with this PR?
Or are you against to merge it?

**Comment by sc0w** [comment]
@raveit65 

offtopic, we have gtk 3.24 since a long time ago, we need to make **gtk3.24** branch ?

**Comment by raveit65** [comment]
> offtopic, we have gtk 3.24 since a long time ago, we need to make gtk3.24 branch ?

As far i know there are no changes needed for gtk+-3.24.
But there is also an option to support different gtk+ branches in one branch, see screenshot how @lukefromdc  handles this for his theme.
https://github.com/mate-desktop/mate-themes/issues/227#issuecomment-400922247
This might be a better option to release one package for all gtk+ branches.

But in the moment my motivation for Mate is zero, because most people from team do not review other reviews, so i am too lazy to start with it.....
The day will come that i will focus my work on fedora, and only doing a bit package releasing here ;)

**Pull request merged**
