### PR TITLE
re-add "Shiny" theme "Window Border"

### PR DESCRIPTION
**Pull request by LeonaDKelso**
The "Shiny" theme was removed in https://github.com/mate-desktop/mate-themes/issues/81 (because there are apparently gtk3 compatibility issues), however, I don't believe there are any compatibility issues with the "Window Border" part of the theme (I compared the diff between "TraditionalOk" and "Shiny" for the "Window Border" and I don't see where there could be any problem). This pull request adds "Shiny Window Border" to the "Window Border" tab in "Customize Theme".

I prefer "TraditionalOk" in general, but have always customized it to use the "Shiny" "Window Border", as this makes the theme look a lot more modern in my opinion. I imagine other users might like to customize in this way as well.

### CODE REVIEW

**Comment by NiceandGently** [comment]
Shiny's theme GTK3 part has tons of issues and needs a complete re-work, ie. buttons, toolbars and and and.....
Are you willing to maintain it and do you have the time to support GTK3-8/10/12/14/16 ?
Sorry, i don't have this time.
We have 9 themes which support GTK3 for all versions more than any other desktop.

**Comment by LeonaDKelso** [comment]
I am not proposing to include the entire "Shiny" theme, just the "Window Border" part. I don't believe there is any compatibility issue with this part. No maintenance is required for the foreseeable future.

Perhaps you aren't aware, if you go to "Appearance Preferences"->"Theme"->"Customize...", you can mix and match parts of different themes. For example, I use "TraditionalOk" for the "Controls" and "Shiny" (known as "Shiny Window Border" in this pull request) for the "Window Border". It's just like the icons and cursors ... you don't need an entire theme to go along with them in order to use them as part of you custom theme.

**Comment by NiceandGently** [comment]
> Perhaps you aren't aware, if you go to "Appearance Preferences"->"Theme"->"Customize...", you can mix and match parts of different themes.

What do you think who i am? LOL
> I am not proposing to include the entire "Shiny" theme, just the "Window Border" part.

...and why you want to override the whole repo with your PR?

**Comment by LeonaDKelso** [comment]
"...and why do you want to override the whole repo with your PR?"

I'm not sure whether you're saying you don't want it or if you're saying there's a problem with the pull request itself. I have never used git before, so I apologize if there's some error. My intention is just to pull 1 file which would allow your users to use the "Shiny" "Window Border". If my intention is not welcome, so be it. I do notice that there are plenty of other "Window Borders" included at least in the Fedora Mate Spin which don't seem to be part of any other theme, for example "WinMe".

**Comment by NiceandGently** [comment]
Please take a look at your PR and see what it does, and calm down before you post things.
The PR is worse, but i'm thinking about to add shiny metacity theme back.

**Comment by LeonaDKelso** [comment]
I am calm. It really doesn't matter to me whether it's included or not, since I can use it personally regardless; I just thought it might help other users.

At the top of this, it says "Files changed 1" -- so I thought things were okay. I presume based upon your comments that they are not, however, I unfortunately am heading out the door soon and cannot take the time at the moment to figure out what I did wrong.

**Comment by NiceandGently** [comment]
Simply click on the changes here in the PR and you will see what every commit does.
I never notice something like this in a PR, but i don't know how you create the PR.
I suggest to open a bugreprt here at mate-themes as reminder for me, and i will add the metacity theme back for myself.
This is easier as to teach you how git works.

Thank you

**Comment by sunweaver** [comment]
@LeonaDKelso: don't get frustrated here, please.

NiceAndGently is doing some awesome work on maintaining mate-themes and he really is _the_ expert on the MATE theming engine. What he says about MATE theming can be considered as _the_ Truth.

About using Git: neither get frustrated about using Git. It takes some time to get behind it, but is a fabulous tool for software development. Stick to it, try it again, fail again. It is worth the hassle. All devs will try to be as patient as possible with newcomers, because newcomers are needed in FLOSS development.

And about your PR... man that is really a f...ed-up PR... if you are more convenient with patch formatted files, check this URL, to see what your PR would do:

https://github.com/mate-desktop/mate-themes/pull/84.patch

In fact, with Github, it is possible to append ".patch" to nearly every URL (a commit, a PR, that is) and you will get the corresponding changeset as a patch file. Much easier to read, much better to understand, much easier to copy+paste.

light+love,
Mike

**Pull request closed without merging**
