### PR TITLE
all themes: Fix: print dialog paper depictions not appearing correctly

### LINKED ISSUE #174: (all themes) print dialog paper depictions not appearing correctly
the paper depictions were mostly fixed in https://github.com/mate-desktop/mate-themes/issues/128, however, a few small glitches remain ...

screen captures are from Mate 1.16.1 in Fedora 25 with mate-themes 3.22.7 and gtk 3.22.10 ...

the shadow on the bottom and right edges is overlapping the paper on the "Page Setup" tab:
overlap

the above issue presents differently in the contrast themes, where the shadow overlaps the entire sheet:
overlap-contrast
overlap-contrast-inverse

In addition, the contrast themes have an issue with missing paper and border colors on the "General" tab (to the right of "Reverse", where "1" and "2" appear):
contrast-general
contrast-inverse-general

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/43858311-all-themes-print-dialog-paper-depictions-not-appearing-correctly?utm_campaign=plugin&utm_content=tracker%2F293056&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F293056&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sc0w**
Fixes #174

### CODE REVIEW

**Comment by lukefromdc** [comment]
Note: I found a bad typo in Menta blocking planned merge, looking for it now

**Comment by lukefromdc** [comment]
That menta-breaking typo I found in testing this is gone in master but still in the just-released gtk3.22 and gtk3.20 tarballs:
https://github.com/mate-desktop/mate-themes/issues/176

**Comment by raveit65** [comment]
Is a border-width < 0 a valid value ?
I noticed i got same results with using border-width=0px or border-style=none.
Sadly, we can do nothing elese with the ugly element, no other color or removing it complete.
Anyways, i am fine with it.

**Comment by sc0w** [comment]
@lukefromdc thanks

@raveit65 

> I noticed i got same results with using border-width=0px or border-style=none.

yes, but it works only in "**Page Setup**", if you use `border-width=0px` or `border-style=none`, you can see this in the "**General**":

noborders

**Pull request merged**
