### PR TITLE
use HighContrastInverse theme from gtk+

### PR DESCRIPTION
**Pull request by raveit65**
Since HighContrastInverse is available by gtk+ we don't need to update our fork.
We simply ship the gtk+-2, metacity theme and a index.theme file which use the gtk+-3 part from gtk+.
That's it.

### CODE REVIEW

**Comment by raveit65** [comment]
@alexarnaud
Please test.

**Comment by lukefromdc** [comment]
I got these errors on running ./autogen.sh --prefix=/usr 

```
Makefile.am: installing './INSTALL'
configure.ac:44: error: required file 'desktop-themes/HighContrastInverse/Makefile.in' not found
configure.ac:44: error: required file 'desktop-themes/HighContrastInverse/gtk-2.0/Makefile.in' not found
configure.ac:44: error: required file 'desktop-themes/HighContrastInverse/gtk-2.0/gtkrc.in' not found
configure.ac:44: error: required file 'desktop-themes/HighContrastInverse/metacity-1/Makefile.in' not found
configure.ac:44: error: required file 'desktop-themes/HighContrastInverse/pixmaps/Makefile.in' not found
desktop-themes/Makefile.am:1: error: required directory desktop-themes/HighContrastInverse does not exist
autoreconf: automake failed with exit status: 1

```

**Comment by raveit65** [comment]
Opps, PR is updated.
Try again please.

**Comment by monsta** [comment]
Looks ok, as I don't use a11y themes anyway.
```
monsta@asylum:~$ ls -l /usr/share/themes/HighContrastInverse/
итого 32
drwxr-xr-x 2 root root  4096 апр 17 21:48 gtk-2.0
-rw-r--r-- 1 root root 10643 мар 31 13:56 index.theme
drwxr-xr-x 2 root root  4096 апр 17 21:48 metacity-1
drwxr-xr-x 2 root root 12288 апр 17 21:48 pixmaps
```
Not sure if this could conflict with old GTK+2 and Metacity themes with the same name from GNOME (did such themes exist?).

**Comment by monsta** [comment]
Also I couldn't find anything from upstream in `/usr/share/themes/HighContrastInverse`. In which version did they add that theme?

**Comment by lukefromdc** [comment]
My current theme directory for HighContrastInverse is empty, and GTK3 does not ship a theme by that name, so I think it's just the HighContrast theme (compiled in the same way as Adwaita rather than in /usr/share/themes) with the colors inverted. Not sure but that's what it looks like. I've always had that theme available, but even back to GTK 3.14 it does not come from a separate theme directory.

**Comment by raveit65** [comment]
The gtk3 parts of themes from gtk+ are shipped with a gresource file nowadays, imo.
For adwaita, adwaita-dark and HighContrast gnome ships a gtk+-2 part, for this reason they need a folder under /usr/share/themes.
If they decided to create a gtk+-2 theme again with a folder, we can rename our folder quickly and ship only a metacity theme plus a index.theme file.
Same what we did for HighContrast theme.
With gtk+-3.20 i simply copied their theme to our repos to avoid porting our old theme to 3.20 syntax.
Since this time we didn't change anything.
So, our theme isn't really an own theme and we can get rid of it safely.
As a side affect this will reduce the workload.

**Comment by monsta** [comment]
Hmm, GResource... can mate-appearance-properties load such themes? Either it can't, or I don't have the necessary packages installed - but I thought it should be a part of GTK+ package itself?

I have the following in mate-appearance-properties:

- Main page:
High Contrast, High Contrast Inverse

- Controls:
HighContrastInverse

- Window border:
HighContrast, HighContrastInverse

- Icons:
ContrastHigh

Both items on the main page seem to come from our index.theme files:
- `/usr/share/themes/ContrastHigh/index.theme`
- `/usr/share/themes/HighContrastInverse/index.theme`

**Comment by raveit65** [comment]
> Hmm, GResource... can mate-appearance-properties load such themes?

It can be load if you choose the edit-menu button. In those list you see the themes.
But without having an index.theme file with gtk/metacity/icon-theme the thumbnail won#t be created.

**Comment by monsta** [comment]
Yeah, I know it won't appear on the main page w/o index.theme. But I also don't see them in GTK+ section when I go to details dialog.

**Comment by monsta** [comment]
Ok, I didn't have `gnome-accessibility-themes` package installed. So I've installed it... and interesting, it has `MetacityTheme` set in its index.theme file.

Our theme - `/usr/share/themes/ContrastHigh/index.theme`:
```
[X-GNOME-Metatheme]
GtkTheme=HighContrast
IconTheme=Adwaita
MetacityTheme=HighContrast
CursorTheme=Adwaita
CursorSize=24
```

Their theme - `/usr/share/themes/HighContrast/index.theme`:
```
Type=X-GNOME-Metatheme
...
GtkTheme=HighContrast
MetacityTheme=HighContrast
IconTheme=Adwaita
CursorTheme=Adwaita
CursorSize=24
```

Now I have duplicate themes in thumbnails :slightly_smiling_face: 

This is `gnome-accessibility-themes 3.22.2` in Debian Stretch, so it's not very new. Should we drop our ContrastHighthen?

**Comment by monsta** [comment]
There was no any HighContrastInverse bits in the package though, maybe it had been added later. I'll check it in more modern systems as well.

**Comment by monsta** [comment]
Ah I see... they don't have `metacity-theme-1.xml`, we should keep our own. But what about our `index.theme`?

**Comment by raveit65** [comment]
In f26
```
[root@mother rave]# yum-deprecated provides /usr/share/themes/HighContrast/index.theme

adwaita-gtk2-theme-3.22.3-2.fc26.i686 : Adwaita gtk2 theme
Quelle      : fedora
Übereinstimmung von:
Dateiname     : /usr/share/themes/HighContrast/index.theme

adwaita-gtk2-theme-3.22.3-2.fc26.x86_64 : Adwaita gtk2 theme
Quelle      : fedora
Übereinstimmung von:
Dateiname     : /usr/share/themes/HighContrast/index.theme
```
```
[root@mother rave]# cat /usr/share/themes/HighContrast/index.theme
<cut>
Encoding=UTF-8
GtkTheme=HighContrast
IconTheme=Adwaita
CursorTheme=Adwaita
CursorSize=24
```
I will check it later in f28. We ship the index.theme file in another dir.
```
[root@mother rave]# cat /usr/share/themes/ContrastHigh/index.theme
<cut>
[X-GNOME-Metatheme]
GtkTheme=HighContrast
IconTheme=Adwaita
MetacityTheme=HighContrast
CursorTheme=Adwaita
CursorSize=24
```

Of course i am happy to remove our fake dir it it isn't necessary.

**Pull request merged**
