### PR TITLE
cursor theme: use HIDIPI cursors

### PR DESCRIPTION
**Pull request by raveit65**
This fixes changing the cursor size with the slider in mate-appearance-properties with HIDPI, see https://github.com/mate-desktop/mate-control-center/pull/340#issuecomment-375865907
Gnome fixed that with that commit https://git.gnome.org/browse/adwaita-icon-theme/commit/?id=7c74b771842536c746a200fc4093818a549c1a2f
So i re-forked the cursor theme and inverted the colors, in result it looks like before for most cursor images.
I think the busy cursor looks a bit different.

As we don't have the the origin .svg to regenerate the .png for all sizes, which are needed to generate the image/x-cursor, i will go this easy and fast way.

### CODE REVIEW

**Comment by flexiondotorg** [comment]
I've tested these on my XPS 15, they look great. I actually prefer the new busy cursor. Any chance you could also make a MATE-Black set based on the originals?

**Comment by raveit65** [comment]
I can fork the normal variant of adwaita theme which is black.

**Comment by lukefromdc** [comment]
I have an issue in my system (unrelated to this) that blocks changing the default cursor and won't be able to effectively test this as a result. Finding that issue could be many hours of debugging locally.

**Comment by raveit65** [comment]
Np.
I just updated make file and rebased the commit. Some cursor-images were missing.

**Pull request merged**
