### PR TITLE
Obsoleting contrasthigh theme

### PR DESCRIPTION
**Pull request by raveit65**
Since GTK+-3.16 the HighContrast theme is shipped by gtk+ himself.
Means it is always installed as gtk+3 is in every default installation.
So, i don't see any reason to ship an copied ContrastHigh theme for us.
For get this working i will add an missing metacity theme for HighContrast which will be installed in /usr/share/themes/HighContrast//metacity-1/ metacity-theme-1.xml
As gnome ships only a  metacity-theme-3.xml version in some distros i don't think i will generate a package conflict.
This step i can backport to all branches if wishes.
This will also remove the big question mark from this theme in mate-appearance-properties ;)
In a second step i want to remove ContrastHigh theme from gtk+-3.20 branch, no need to do this for older branches.
Of course the ContrasHighInverse theme will stay as gtk+ ship only a dark theme version, which can't be use by Mate.

Some questions to distro maintainers.
1. Did your distro ship a metacity theme for HighContrast theme and which version?
2. I know for most of you gtk+-3.20 is future music, but is this step acceptable for you?

Thank you , this will reduce my work overload.
Any thoughts?
@monsta 
@flexiondotorg 
@willysr 
@clefebvre 
@XRevan86 
@stefano-k 
@sunveawer 
@lukefromdc 
@ksamak

### CODE REVIEW

**Comment by willysr** [comment]
Slackware 14.2 will use GTK+3-3.18.x and indeed we don't have metacity-theme-1.xml, but metacity-theme-3.xml

ls /usr/share/themes/HighContrast/metacity-1/
metacity-theme-3.xml

i'm fine with this idea, so +1

**Comment by monsta** [comment]
> Since GTK+-3.16 the HighContrast theme is shipped by gtk+ himself.

> In a second step i want to remove ContrastHigh theme from gtk+-3.20 branch, no need to do this for older branches.

Hmm... but if it's shipped in GTK+ >= 3.16, then it can be removed from 3.18 and 3.16 branches as well?

Anyway, I'm fine with this PR :smile:

**Comment by raveit65** [comment]
> Hmm... but if it's shipped in GTK+ >= 3.16, then it can be removed from 3.18 and 3.16 branches as well?

Sure, this is possible, but there are distros which use our theme for this gtk+ versions since a long time. So, it is possible that i remove a theme which is used by some users.
' Oh no, where is my theme after an update'
This is something which i don't want to to if it is not necessary.

**Comment by monsta** [comment]
Ah, right... I didn't think that they won't be switched to GTK+ HighContrast theme automatically :smile:

**Comment by lukefromdc** [comment]
Good point: a missing theme can REALLY bother someone. In my case.the fact
that the old UbuntuStudio theme wasn't supported by GTK3 drove me to learn
to write themes, but surely some people just responded with "gtk3 sucks" and 
either didn't update or went back to Windows.

**Comment by raveit65** [comment]
merged
177c67e0896e6cf7ac9822a60a3ccbd9ace00778
https://github.com/mate-desktop/mate-themes/commit/177c67e0896e6cf7ac9822a60a3ccbd9ace00778

**Pull request closed without merging**
