### PR TITLE
Fix cahrpick Yaru

### PR DESCRIPTION
**Pull request by blue-devil-93**
Fix charpick Yaru

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
Behavior with this still doesn't match the other MATE themes and Adwaita in that a selected character once clicked on only retains its highlight until the mouse is moved away from it. In the other themes the selected character stays highlighted until another is selected.

Note that I do not know how to actually use this applet so I do not know which is actually the preferred behavior

**Comment by blue-devil-93** [comment]
Blue-Menta and Menta seems to be the ones other themes schould bevsimilar
too. Look at it  these days @lukefromdc. Current solution looks cleaner but
if its  supposed to act differently i try again fixing it.

**Comment by raveit65** [comment]
As mate-themes maintainer you can create a branch for a PR directly on our repo. No need to fork the repo to your github repo ;)

**Comment by raveit65** [comment]
It's the toggle css class selector, which is missing in new code, see gtk3-inspector
Bildschirmfoto zu 2021-09-17 18-26-15

With this code based on yours in gtk3-inspector i have the 3 button states. Normal, hover and button is selected afer button released.
```
.mate-panel-menu-bar #PanelApplet button.flat.toggle {
      background-color: transparent;
      color: $_base_fg_color;
      border-radius: 4px;
      border-color: $borders_color;
      border-right-width: 1px;
      border-left-width: 1px; 
      border-color: rgba(0,0,0,0.0);
      box-shadow: inset 0px 1px $borders_color,inset 0px -1px $borders_color, inset 1px 0px $borders_color,inset -1px 0px $borders_color;
      padding-left: 2px;
      padding-right: 2px
}

.mate-panel-menu-bar #PanelApplet button.flat.toggle:checked,
.mate-panel-menu-bar #PanelApplet button.flat.toggle:checked:hover,
.mate-panel-menu-bar #PanelApplet button.flat.toggle:hover:active {
    background-image: linear-gradient(to bottom,
                                      shade (@theme_bg_color, 1.0),
                                      shade (@theme_bg_color, 0.82));
    color: shade (@theme_fg_color, 1.00);
}

.mate-panel-menu-bar #PanelApplet button.flat.toggle:hover {
background-color: transparent;
      color: $_base_fg_color;
      border-radius: 4px;
      border-color: $borders_color;
      border-right-width: 1px;
      border-left-width: 1px; 
      border-color: rgba(0,0,0,0.0);
      box-shadow: inset 0px 1px $borders_color,inset 0px -1px $borders_color, inset 1px 0px $borders_color,inset -1px 0px $borders_color;
      padding-left: 2px;
      padding-right: 2px
}
```
Those 3 button states you see in all other mate themes. Of course not with Adwaita because they don't style single applications like the panel or panel-applets.

**Comment by blue-devil-93** [comment]
@raveit65
My problem is i tend to always push commits to master and thats why  i did
fork it and then create a pull request. :)

Thanks a lot  now i do get the  idea of how its done correctly with this
toggle button. I' ll post it on sunday corrected.

My current patch as it is now  does change the drawing behaviour but its
missing the word toggle and definitions are different. The last button
selected has to stay selected until another one is selected.

**Comment by raveit65** [comment]
`git checkout -b new-branch-name` does the magic :)
But up to you.....

**Comment by blue-devil-93** [comment]
@raveit65 
did now try again to patch it. hope it gets now more correct behaviour.  Not defined as toggle button.
reason is charpich button   has to be different from window tasklist.

**Review by lukefromdc — APPROVED** [review]
This now works as expected, and like the other MATE themes. Subtle but effective highlighting here

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
