### PR TITLE
Port Blue-Submarine to gtk3.20

### PR DESCRIPTION
**Pull request by lukefromdc**
Same files as Green-Submarine except for gtk.css and settings.ini, which contain the color information and required no changes. Title at top of gtk-widgets.css adjusted to reflect that it is for Blue-Submarine.

### CODE REVIEW

**Comment by raveit65** [comment]
Hi,
I 'm a bit ill so i couldn't answer before.
Thanks for you efforts, but there is a different with box-shadows of active/hover state between the submarine themes at some places.
blue-submarine:
```
-.entry:focus {
-    box-shadow: inset  0px  1px shade (@theme_selected_bg_color, 1.3),
-                inset  1px  0px shade (@theme_selected_bg_color, 1.3),
-                inset -1px  0px shade (@theme_selected_bg_color, 1.3),
-                inset  0px -1px shade (@theme_selected_bg_color, 1.3);
```
green-submarine:
```
+entry:focus {
+    box-shadow: inset  0px  1px shade(@selected_bg_color, 1.05),
+                inset  1px  0px shade(@selected_bg_color, 0.97),
+                inset -1px  0px shade(@selected_bg_color, 0.93),
+                inset  0px -1px shade(@selected_bg_color, 0.93);
```
Also i thinks some selectors are wrong, ie. .primary-toolbar  --> toolbar.primary-toolbar , see raw BlueMenta port.
For this reason you have some button jumpings.
I would prefer to finished green-submarine first and than start with blue-submarine.

**Comment by lukefromdc** [comment]
OK, close the PR for now, treat is as a source of raw material. I spotted the 
button jumping last night in both versions (have them installed locally), the 
button code is quite complex so I may or may not be able to find it. Observed
it in the first three Nemo toobar buttons and the mate-panel show-desktop
button only on my setup. Cause of this in gtk3.19 is usually a border defined
in one widget state but not another.  Saw this in menus when I started, borders
now routinely increase widget size and must be the same in every widget state
or it jumps.

**Comment by lukefromdc** [comment]
I did some digging with gtk-inspector, found .primary-toolbar as the style class
applied to toolbar. Therefore toolbar,  toolbar.primary-toobar and .primary-toolbar 
should work, if primary-toolbar works that is undocumented behavior.

**Comment by raveit65** [comment]
Thanks for your work!

**Pull request closed without merging**
